#ifndef MARTINSM850DMXRECIEVER_MARTINSM850FOGMACHINE_H
#define MARTINSM850DMXRECIEVER_MARTINSM850FOGMACHINE_H

void init_DIN();
void fog();
void stop_fog();

#endif //MARTINSM850DMXRECIEVER_MARTINSM850FOGMACHINE_H
